[tool.poetry]
name = "milatools"
version = "0.0.7"
description = "Tools to work with the Mila cluster"
authors = ["Olivier Breuleux <breuleux@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/mila-iqia/milatools"
repository = "https://github.com/mila-iqia/milatools"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
blessed = "^1.18.1"
coleo = "0.2.5"
ptera = "0.4.2"
sshconf = "^0.2.2"
questionary = "^1.10.0"
Fabric = "^2.7.0"

[tool.poetry.dev-dependencies]
black = "^21.8b0"
isort = "^5.9.3"

[tool.poetry.scripts]
mila = "milatools.cli.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
